i---
- name: Tuesday Challenge
  hosts: localhost
  connection: local
  gather_facts: no

  
  tasks:
    - name: create a directory
      file:
        dest: challenge
        state: directory

   - name: creating a file
     copy:
       dest: local/challengefile.txt
       content: "Success!"
       
